### ISSUE TITLE
Organize game state

### ISSUE THREAD

**Issue by RoboticWater** [DGG-Incremental/DGG-Incremental#11]
Right now, resources and most other game state variables are at the base of the game state, which is pretty messy. It also means that the UI has to directly query for each individual resource, rather than just iterating through an array or object of them.

I suggest that we organize the game state into modules, e.g. gameState.resources and gameState.upgrades so that our state is organized going forward.

**Comment by Citizen-Thayne** [comment]
I think we've done a bit of this recently. Feel good to close? @RoboticWater

**Comment by RoboticWater** [comment]
Yeah, I like where it's at currently with the resource list.
