### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by Citizen-Thayne** [DGG-Incremental/DGG-Incremental#8]
Replace the React favicon with this: 

![](https://cdn.discordapp.com/attachments/673678711522066458/679535616899285013/clicker_-_avatar.png)

**Comment by RoboticWater** [comment]
![favicon](https://user-images.githubusercontent.com/5916107/74790442-898bf400-5285-11ea-8f08-6799a8c74228.png)
Here's a version with the background removed.

**Comment by RoboticWater** [comment]
![favicon](https://user-images.githubusercontent.com/5916107/74790505-c0faa080-5285-11ea-99ef-1fc8176be7e7.png)
Here we go.
